language: python

python:
  - "3.9"

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/conda
  - export PATH="$HOME/conda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update --quiet -n root -q conda
  - conda info -a
  - conda env create --quiet -f env.yml
  - source activate site
  - curl --create-dirs --output content/data/publications.bib http://andreanjos.org/cv/publications.bib

script:
  - pelican

notifications:
  email:
    on_success: always
    on_failure: always

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: output
  repo: anjos/anjos.github.io
  target_branch: master
  on:
    tags: true
