# SPDX-FileCopyrightText: Copyright © 2026 Idiap Research Institute <contact@idiap.ch>
#
# SPDX-License-Identifier: BSD-3-Clause
# Temporary warning-only check for the correct, currently unavailable
# IMAGIN-AIR project URL. Remove this entry and its lychee.toml exclusion
# once the page is available. With no exclude key, include is an allowlist.
no_progress = true
timeout = 20
max_retries = 0
accept = ["200..=206", "429"]
include = ["^https://www\\.idiap\\.ch/en/projects/imagin-air$"]
