# SPDX-FileCopyrightText: Copyright © 2026 Idiap Research Institute <contact@idiap.ch>
#
# SPDX-License-Identifier: BSD-3-Clause
# Temporary warning-only checks for idiap.ch and every subdomain while the
# domain is unstable. Keep this allowlist in step with lychee.toml's exclusion.
# No exclude key: include is an allowlist only when exclude is absent.
no_progress = true
cache = true
max_cache_age = "2d"
accept = ["200..=206", "429"]
timeout = 5
max_retries = 1
retry_wait_time = 1
include = ["^https?://([A-Za-z0-9-]+\\.)*idiap\\.ch(:[0-9]+)?(/|$)"]
