# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: deploy to anjos.github.io

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.30.0
          cache: true
      - run: pixi run gh-action

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
            deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
            external_repository: anjos/anjos.github.io
            publish_dir: ./output
            publish_branch: main
            cname: anjos.ai
