name: deploy to anjos.github.io

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: false
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: site
          environment-file: env.yml

      - name: Build
        shell: bash -l {0}
        run: |
          conda info -a
          curl --create-dirs --output content/data/publications.bib http://andreanjos.org/cv/publications.bib
          pelican

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
            deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
            publish_dir: ./output
            external_repository: anjos/anjos.github.io
            publish_branch: master
            cname: andreanjos.org
